version: "3.9"

networks:
    default:
        name: miniScrap
services:
  backend:
      build: ./backend
      ports:
        - 3000:3000
      restart: on-failure

  frontend:
      build: ./frontend
      ports:
        - 4173:4173
      depends_on:
        - backend
      restart: on-failure